name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run lint
      - run: npm run test:coverage
        env:
          CI: true
